version: '2'
services:
    testglx-app:
        image: testglx
        external_links:
            - testglx-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/testglx?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testglx-mysql:
        extends:
            file: mysql.yml
            service: testglx-mysql
